const tripLang = {
  newTrip_en: 'New Trip',
  newTrip_ru: 'Создать Поездку',
  newTrip_pl: 'Nowa Podróż',
  newTrip_de: 'Neue Reise',
  newTrip_zh: '新旅行',

  createNewTrip_en: 'Create new trip',
  createNewTrip_ru: 'Создать новую поездку',
  createNewTrip_pl: 'Stwóż nową podróż',
  createNewTrip_de: 'Neue Reise erstellen',
  createNewTrip_zh: '建立新行程',

  tripName_en: 'Trip name',
  tripName_ru: 'Название путешествия',
  tripName_pl: 'Nazwa podróży',
  tripName_de: 'Name der Reise',
  tripName_zh: '旅行名稱',

  your1stDestination_en: 'Your first destination',
  your1stDestination_ru: 'Первый пункт маршрута',
  your1stDestination_pl: 'Pierwszy punkt podróży',
  your1stDestination_de: 'Dein erstes Ziel',
  your1stDestination_zh: '您的第一個目的地',

  startDate_en: 'Start date',
  startDate_ru: 'Дата начала',
  startDate_pl: 'Data początku',
  startDate_de: 'Startdatum',
  startDate_zh: '開始日期',

  endDate_en: 'End date',
  endDate_ru: 'Дата окончания',
  endDate_pl: 'Data zakończenia',
  endDate_de: 'Endtermin',
  endDate_zh: '結束日期',

  createTrip_en: 'Create',
  createTrip_ru: 'Создать',
  createTrip_pl: 'Stwóż',
  createTrip_de: 'Erstellen',
  createTrip_zh: '創造',

  notAuthorized_en: 'You a not authorized yet!',
  notAuthorized_ru: 'Вы ещё не авторизированы!',
  notAuthorized_pl: 'Nie jesteś jeszcze zalogowany(-a)!',
  notAuthorized_de: 'Sie sind noch nicht autorisiert!',
  notAuthorized_zh: '您尚未授權！',

  toBeAbleLogIn_en: 'To be able to add new trips, please log in or sign up.',
  toBeAbleLogIn_ru: 'Чтобы иметь возмоность создавать новые поездки, войдите или зарегистрируйтесь.',
  toBeAbleLogIn_pl: 'Żeby mieć możliwość stwarzać nowe podróże, zaloguj się albo zarejestruj się.',
  toBeAbleLogIn_de: 'Um neue Reisen hinzufügen zu können, melden Sie sich bitte an oder melden Sie sich an.',
  toBeAbleLogIn_zh: '為了能夠添加新行程，請登錄或註冊。',

  changeTripName_en: 'Change trip name',
  changeTripName_ru: 'Изменить название поездки',
  changeTripName_pl: 'Zmienić nazwę podróży',
  changeTripName_de: 'Ändern Sie den Namen der Reise',
  changeTripName_zh: '更改行程名稱',

  change_en: 'Change',
  change_ru: 'Изменить',
  change_pl: 'Zmienić',
  change_de: 'Veränderung',
  change_zh: '更改',

  changeTripDates_en: 'Change trip dates',
  changeTripDates_ru: 'Изменить даты поездки',
  changeTripDates_pl: 'Zmienić daty podróży',
  changeTripDates_de: 'Reisedaten ändern',
  changeTripDates_zh: '更改行程日期',

  sureWantRemoveTrip_en: 'Are you sure you want remove this trip?',
  sureWantRemoveTrip_ru: 'Вы уверены, что хотите удалить эту поездку?',
  sureWantRemoveTrip_pl: 'Czy na pewno chcesz usunąć tę podróż?',
  sureWantRemoveTrip_de: 'Sind Sie sicher, dass Sie diese Reise entfernen möchten?',
  sureWantRemoveTrip_zh: '您確定要刪除此行嗎？',

  ifRemoveAllDeleted_en: 'If you remove the trip, all settings will be permanently deleted!',
  ifRemoveAllDeleted_ru: 'Если удалите поездку, то все данные, связанные с ней, также будут удалены!',
  ifRemoveAllDeleted_pl: 'Jeżeli usuniesz podróż, to wszystkie dane związane z nią, również będą usunięte!',
  ifRemoveAllDeleted_de: 'Wenn Sie die Reise entfernen, werden alle Einstellungen dauerhaft gelöscht!',
  ifRemoveAllDeleted_zh: '如果您取消行程，所有設置將被永久刪除！',

  cancel_en: 'Cancel',
  cancel_ru: 'Отмена',
  cancel_pl: 'Cofnij',
  cancel_de: 'Stornieren',
  cancel_zh: '取消',

  remove_en: 'Remove',
  remove_ru: 'Удалить',
  remove_pl: 'Usuń',
  remove_de: 'Entfernen',
  remove_zh: '去掉',

  addDestination_en: 'Add destination',
  addDestination_ru: 'Добавить пункт маршрута',
  addDestination_pl: 'Dodaj punkt podróży',
  addDestination_de: 'Ziel hinzufügen',
  addDestination_zh: '添加目的地',

  add_en: 'Add',
  add_ru: 'Добавить',
  add_pl: 'Dodaj',
  add_de: 'Hinzufügen',
  add_zh: '加',

  removeDestination_en: 'Remove destination?',
  removeDestination_ru: 'Удалить пункт маршрута?',
  removeDestination_pl: 'Usunąć punkt podróży?',
  removeDestination_de: 'Ziel entfernen?',
  removeDestination_zh: '刪除目的地？',

  sureWantDelete_en: 'Are you sure you want delete',
  sureWantDelete_ru: 'Вы уверены, что хотите удалить страницу',
  sureWantDelete_pl: 'Czy na pewno chcesz usunąć stronę',
  sureWantDelete_de: 'Sind Sie sicher, dass Sie löschen möchten?',
  sureWantDelete_zh: '確定要刪除嗎',

  ifRemovePermDeleted_en: 'page? If you remove it, all your notes and To Do list will be permanently deleted!',
  ifRemovePermDeleted_ru: '? Если вы удалите её, то все ваши данные, связанные с этим местом также будут удалены!',
  ifRemovePermDeleted_pl: '? Jeżeli usuniesz, to wszystkie dane, związane z tym miejscem, również będą usunięte!',
  ifRemovePermDeleted_de: 'Seite? Wenn Sie es entfernen, werden alle Ihre Notizen und Aufgabenlisten dauerhaft gelöscht!',
  ifRemovePermDeleted_zh: '頁？ 如果刪除它，所有筆記和“待辦事項”列表將被永久刪除！',

  noTripsCreateAndPlanJourney_en: 'You have no trips yet. Create new trip and plan your journey!',
  noTripsCreateAndPlanJourney_ru: 'У вас ещё нет поездок. Создайте поездку и запланируйте ваше путешествие!',
  noTripsCreateAndPlanJourney_pl: 'Nie masz jeszcze podróży. Stwóż podróż i zaplanuj swoją przygodę!',
  noTripsCreateAndPlanJourney_de: 'Sie haben noch keine Reisen. Erstellen Sie eine neue Reise und planen Sie Ihre Reise!',
  noTripsCreateAndPlanJourney_zh: '您還沒有旅行。 創建新行程併計劃您的行程！',

  ifYouTravelDoNotForgetPassport_en: 'If you are traveling abroad, don\'t forget your passport!',
  ifYouTravelDoNotForgetPassport_ru: 'Если вы выезжаете за границу, не забудьте взять ваш пасспорт!',
  ifYouTravelDoNotForgetPassport_pl: 'Jeżeli podróżujesz za granicę, nie zapomnij wziąć paszport!',
  ifYouTravelDoNotForgetPassport_de: 'Wenn Sie ins Ausland reisen, vergessen Sie Ihren Reisepass nicht!',
  ifYouTravelDoNotForgetPassport_zh: '如果您出国旅行，请不要忘记护照！',
};

export default tripLang;
