const tripLang = {
  newTrip_en: 'New Trip',
  newTrip_ru: 'Создать Поездку',
  newTrip_pl: 'Nowa Podróż',
  newTrip_de: '',
  newTrip_zh: '',

  createNewTrip_en: 'Create new trip',
  createNewTrip_ru: 'Создать новую поездку',
  createNewTrip_pl: 'Stwóż nową podróż',
  createNewTrip_de: '',
  createNewTrip_zh: '',

  tripName_en: 'Trip name',
  tripName_ru: 'Название путешествия',
  tripName_pl: 'Nazwa podróży',
  tripName_de: '',
  tripName_zh: '',

  your1stDestination_en: 'Your first destination',
  your1stDestination_ru: 'Первый пункт маршрута',
  your1stDestination_pl: 'Pierwszy punkt podróży',
  your1stDestination_de: '',
  your1stDestination_zh: '',

  startDate_en: 'Start date',
  startDate_ru: 'Дата начала',
  startDate_pl: 'Data początku',
  startDate_de: '',
  startDate_zh: '',

  endDate_en: 'End date',
  endDate_ru: 'Дата окончания',
  endDate_pl: 'Data zakończenia',
  endDate_de: '',
  endDate_zh: '',

  createTrip_en: 'Create',
  createTrip_ru: 'Создать',
  createTrip_pl: 'Stwóż',
  createTrip_de: '',
  createTrip_zh: '',

  notAuthorized_en: 'You a not authorized yet!',
  notAuthorized_ru: 'Вы ещё не авторизированы!',
  notAuthorized_pl: 'Nie jesteś jeszcze zalogowany(-a)!',
  notAuthorized_de: '',
  notAuthorized_zh: '',

  toBeAbleLogIn_en: 'To be able to add new trips, please log in or sign up.',
  toBeAbleLogIn_ru: 'Чтобы иметь возмоность создавать новые поездки, войдите или зарегистрируйтесь.',
  toBeAbleLogIn_pl: 'Żeby mieć możliwość stwarzać nowe podróże, zaloguj się albo zarejestruj się.',
  toBeAbleLogIn_de: '',
  toBeAbleLogIn_zh: '',

  changeTripName_en: 'Change trip name',
  changeTripName_ru: 'Изменить название поездки',
  changeTripName_pl: 'Zmienić nazwę podróży',
  changeTripName_de: '',
  changeTripName_zh: '',

  change_en: 'Change',
  change_ru: 'Изменить',
  change_pl: 'Zmienić',
  change_de: '',
  change_zh: '',

  changeTripDates_en: 'Change trip dates',
  changeTripDates_ru: 'Изменить даты поездки',
  changeTripDates_pl: 'Zmienić daty podróży',
  changeTripDates_de: '',
  changeTripDates_zh: '',

  sureWantRemoveTrip_en: 'Are you sure you want remove this trip?',
  sureWantRemoveTrip_ru: 'Вы уверены, что хотите удалить эту поездку?',
  sureWantRemoveTrip_pl: 'Czy na pewno chcesz usunąć tę podróż?',
  sureWantRemoveTrip_de: '',
  sureWantRemoveTrip_zh: '',

  ifRemoveAllDeleted_en: 'If you remove the trip, all settings will be permanently deleted!',
  ifRemoveAllDeleted_ru: 'Если удалите поездку, то все данные, связанные с ней, также будут удалены!',
  ifRemoveAllDeleted_pl: 'Jeżeli usuniesz podróż, to wszystkie dane związane z nią, również będą usunięte!',
  ifRemoveAllDeleted_de: '',
  ifRemoveAllDeleted_zh: '',

  cancel_en: 'Cancel',
  cancel_ru: 'Отмена',
  cancel_pl: 'Cofnij',
  cancel_de: '',
  cancel_zh: '',

  remove_en: 'Remove',
  remove_ru: 'Удалить',
  remove_pl: 'Usuń',
  remove_de: '',
  remove_zh: '',

  addDestination_en: 'Add destination',
  addDestination_ru: 'Добавить пункт маршрута',
  addDestination_pl: 'Dodaj punkt podróży',
  addDestination_de: '',
  addDestination_zh: '',

  add_en: 'Add',
  add_ru: 'Добавить',
  add_pl: 'Dodaj',
  add_de: '',
  add_zh: '',

  removeDestination_en: 'Remove destination?',
  removeDestination_ru: 'Удалить пункт маршрута?',
  removeDestination_pl: 'Usunąć punkt podróży?',
  removeDestination_de: '',
  removeDestination_zh: '',

  sureWantDelete_en: 'Are you sure you want delete',
  sureWantDelete_ru: 'Вы уверены, что хотите удалить страницу',
  sureWantDelete_pl: 'Czy na pewno chcesz usunąć stronę',
  sureWantDelete_de: '',
  sureWantDelete_zh: '',

  ifRemovePermDeleted_en: 'page? If you remove it, all your notes and To Do list will be permanently deleted!',
  ifRemovePermDeleted_ru: '? Если вы удалите её, то все ваши данные, связанные с этим местом также будут удалены!',
  ifRemovePermDeleted_pl: '? Jeżeli usuniesz, to wszystkie dane, związane z tym miejscem, również będą usunięte!',
  ifRemovePermDeleted_de: '',
  ifRemovePermDeleted_zh: '',

  noTripsCreateAndPlanJourney_en: 'You have no trips yet. Create new trip and plan your journey!',
  noTripsCreateAndPlanJourney_ru: 'У вас ещё нет поездок. Создайте поездку и запланируйте ваше путешествие!',
  noTripsCreateAndPlanJourney_pl: 'Nie masz jeszcze podróży. Stwóż podróż i zaplanuj swoją przygodę!',
  noTripsCreateAndPlanJourney_de: '',
  noTripsCreateAndPlanJourney_zh: '',
};

export default tripLang;
